# Generated by Django 2.0 on 2018-09-19 15:01

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ika', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.CharField(max_length=4, unique=True)),
                ('secret_key', models.UUIDField(default=uuid.uuid4)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='ika.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
