# Generated by Django 2.0 on 2018-09-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ika', '0002_auto_20180919_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='channels',
            field=models.ManyToManyField(related_name='apps', to='ika.Channel'),
        ),
    ]
