# Generated by Django 2.0 on 2018-09-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ika', '0003_application_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
